config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
#  hello/urls.py
from django.conf.urls import url
from django.shortcuts import render
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('about', views.about_page_view, name='about'),
    path('contact_us', views.contact_us_page_view, name='contact_us'),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
#  hello/views.py
import datetime

from django.shortcuts import render


def home_page_view(request):  # para renderizar a página home.html teremos a função home_page_view
    lista = ["Rosas", "Camomilas", "Lilás", "Túlipas"]

    context = {
        'hora': datetime.datetime.now(),
        'lista': lista,
    }
    return render(request, 'website/home.html', context)


def about_page_view(request):
    return render(request, 'website/about.html')


def contact_us_page_view(request):
    return render(request, 'website/contact_us.html')

website/templates/website/about.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>About</h3>
    <p>Programação Web - Lab 6</p>
{% endblock %}

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>21802381 - PW</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <header class="jumbotron text-center">
        <h1>PW - 21802381</h1>
        <p>Website Django e Python</p>
        <nav>
            <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
            <a href="{% url 'website:about' %}" class="btn btn-info">About</a>
            <a href="{% url 'website:contact_us' %}" class="btn btn-info">Contact Us</a>
        </nav>
    </header>
    <article class="container">
        <main class="col-sm-6">
            {% block main %}
	        {% endblock main %}
        </main>
        <aside class="col-sm-6">
            {% load static %}
            <img src="{% static 'website/images/imagem.jpg' %}" alt="image_1">
        </aside>
    </article>
    <footer>Programação Web 20/21 ULHT</footer>
</body>
</html>

website/templates/website/contact_us.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Contact Us</h3>
    <p>Contact us via email: a21802381@ulusofona.pt </p>
{% endblock %}

website/templates/website/home.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Home</h3>
    <p>This is the home page</p>


    {{ hora }}
    {% if hora < 12 %}
        <p>Bom dia, são {{ hora }} horas.</p>
    {% else %}
        <p>Boa tarde, são {{ hora }} horas.</p>
    {% endif %}

    <p>Exemplos de flores</p>
     <ul>
    {% for item in lista %}
        <li>{{ item }}</li>
    {% endfor %}
    </ul>


{% endblock %}